module GrowsurfRuby
  module Resources
    class Account
      def create: (
        email: String,
        ?company: String,
        ?first_name: String,
        ?last_name: String,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::Models::AccountCreateResponse

      def initialize: (client: GrowsurfRuby::Client) -> void
    end
  end
end
