module GrowsurfRuby
  module Resources
    class Campaign
      attr_reader participant: GrowsurfRuby::Resources::Campaign::Participant

      attr_reader reward: GrowsurfRuby::Resources::Campaign::Reward

      attr_reader commission: GrowsurfRuby::Resources::Campaign::Commission

      attr_reader rewards: GrowsurfRuby::Resources::Campaign::Rewards

      attr_reader design: GrowsurfRuby::Resources::Campaign::Design

      attr_reader emails: GrowsurfRuby::Resources::Campaign::Emails

      attr_reader options: GrowsurfRuby::Resources::Campaign::Options

      attr_reader installation: GrowsurfRuby::Resources::Campaign::Installation

      attr_reader webhooks: GrowsurfRuby::Resources::Campaign::Webhooks

      def retrieve: (
        String id,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::CampaignAPI

      def list: (
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::Models::CampaignListResponse

      def create: (
        type: GrowsurfRuby::Models::CampaignCreateParams::type_,
        ?company_logo_image_url: String,
        ?company_name: String,
        ?currency_iso: String,
        ?name: String,
        ?rewards: ::Array[GrowsurfRuby::Campaign::RewardCreateParams],
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::CampaignAPI

      def update: (
        String id,
        ?company_logo_image_url: String,
        ?company_name: String,
        ?name: String,
        ?status: GrowsurfRuby::Models::CampaignUpdateParams::status,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::CampaignAPI

      def clone: (
        String id,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::CampaignAPI

      def create_mobile_participant_token: (
        String id,
        email: String,
        ?fingerprint: String,
        ?first_name: String,
        ?ip_address: String,
        ?last_name: String,
        ?metadata: ::Hash[Symbol, top],
        ?mobile_instance_id: String,
        ?referral_status: GrowsurfRuby::Models::Campaign::Create::referral_status,
        ?referred_by: String,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::Models::CampaignCreateMobileParticipantTokenResponse

      def list_commissions: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?status: GrowsurfRuby::Models::CampaignListCommissionsParams::status,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::ParticipantCommissionList

      def list_leaderboard: (
        String id,
        ?is_monthly: bool,
        ?leaderboard_type: GrowsurfRuby::Models::CampaignListLeaderboardParams::leaderboard_type,
        ?limit: Integer,
        ?next_id: String,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::ParticipantList

      def list_participants: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::ParticipantList

      def list_payouts: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?status: GrowsurfRuby::Models::CampaignListPayoutsParams::status,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::ParticipantPayoutList

      def list_referrals: (
        String id,
        ?desc: bool,
        ?email: String,
        ?first_name: String,
        ?last_name: String,
        ?limit: Integer,
        ?next_id: String,
        ?offset: Integer,
        ?referral_status: GrowsurfRuby::Models::Campaign::referral_status,
        ?sort_by: GrowsurfRuby::Models::CampaignListReferralsParams::sort_by,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::ReferralList

      def retrieve_analytics: (
        String id,
        ?days: Integer,
        ?end_date: Integer,
        ?include: String,
        ?interval: GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval,
        ?start_date: Integer,
        ?request_options: GrowsurfRuby::request_opts
      ) -> GrowsurfRuby::Models::CampaignRetrieveAnalyticsResponse

      def initialize: (client: GrowsurfRuby::Client) -> void
    end
  end
end
