module GrowsurfRuby
  module Campaign = GrowsurfRuby::Models::Campaign

  class CampaignAPI = GrowsurfRuby::Models::CampaignAPI

  class CampaignCreateMobileParticipantTokenParams = GrowsurfRuby::Models::CampaignCreateMobileParticipantTokenParams

  class CampaignCreateParams = GrowsurfRuby::Models::CampaignCreateParams

  class CampaignListCommissionsParams = GrowsurfRuby::Models::CampaignListCommissionsParams

  class CampaignListLeaderboardParams = GrowsurfRuby::Models::CampaignListLeaderboardParams

  class CampaignListParams = GrowsurfRuby::Models::CampaignListParams

  class CampaignListParticipantsParams = GrowsurfRuby::Models::CampaignListParticipantsParams

  class CampaignListPayoutsParams = GrowsurfRuby::Models::CampaignListPayoutsParams

  class CampaignListReferralsParams = GrowsurfRuby::Models::CampaignListReferralsParams

  class CampaignRetrieveAnalyticsParams = GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams

  class CampaignRetrieveParams = GrowsurfRuby::Models::CampaignRetrieveParams

  class CampaignUpdateParams = GrowsurfRuby::Models::CampaignUpdateParams

  class CommissionStructure = GrowsurfRuby::Models::CommissionStructure

  class ParticipantCommissionList = GrowsurfRuby::Models::ParticipantCommissionList

  class ParticipantList = GrowsurfRuby::Models::ParticipantList

  class ParticipantPayoutList = GrowsurfRuby::Models::ParticipantPayoutList

  class ReferralList = GrowsurfRuby::Models::ReferralList
end
