module Growsurf
  module Campaign = Growsurf::Models::Campaign

  class CampaignAPI = Growsurf::Models::CampaignAPI

  class CampaignListCommissionsParams = Growsurf::Models::CampaignListCommissionsParams

  class CampaignListLeaderboardParams = Growsurf::Models::CampaignListLeaderboardParams

  class CampaignListParams = Growsurf::Models::CampaignListParams

  class CampaignListParticipantsParams = Growsurf::Models::CampaignListParticipantsParams

  class CampaignListPayoutsParams = Growsurf::Models::CampaignListPayoutsParams

  class CampaignListReferralsParams = Growsurf::Models::CampaignListReferralsParams

  class CampaignRetrieveAnalyticsParams = Growsurf::Models::CampaignRetrieveAnalyticsParams

  class CampaignRetrieveParams = Growsurf::Models::CampaignRetrieveParams

  class CommissionStructure = Growsurf::Models::CommissionStructure

  class ParticipantCommissionList = Growsurf::Models::ParticipantCommissionList

  class ParticipantList = Growsurf::Models::ParticipantList

  class ParticipantPayoutList = Growsurf::Models::ParticipantPayoutList

  class ReferralList = Growsurf::Models::ReferralList
end
