module GrowsurfRuby
  module Models
    type campaign_retrieve_analytics_params =
      {
        id: String,
        days: Integer,
        end_date: Integer,
        include: String,
        interval: GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval,
        start_date: Integer
      }
      & GrowsurfRuby::Internal::Type::request_parameters

    class CampaignRetrieveAnalyticsParams < GrowsurfRuby::Internal::Type::BaseModel
      extend GrowsurfRuby::Internal::Type::RequestParameters::Converter
      include GrowsurfRuby::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader days: Integer?

      def days=: (Integer) -> Integer

      attr_reader end_date: Integer?

      def end_date=: (Integer) -> Integer

      attr_reader include: String?

      def include=: (String) -> String

      attr_reader interval: GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval?

      def interval=: (
        GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval
      ) -> GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval

      attr_reader start_date: Integer?

      def start_date=: (Integer) -> Integer

      def initialize: (
        id: String,
        ?days: Integer,
        ?end_date: Integer,
        ?include: String,
        ?interval: GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval,
        ?start_date: Integer,
        ?request_options: GrowsurfRuby::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        days: Integer,
        end_date: Integer,
        include: String,
        interval: GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval,
        start_date: Integer,
        request_options: GrowsurfRuby::RequestOptions
      }

      type interval = :day | :week | :month | :total

      module Interval
        extend GrowsurfRuby::Internal::Type::Enum

        DAY: :day
        WEEK: :week
        MONTH: :month
        TOTAL: :total

        def self?.values: -> ::Array[GrowsurfRuby::Models::CampaignRetrieveAnalyticsParams::interval]
      end
    end
  end
end
