module GrowsurfRuby
  module Models
    type referral_list =
      {
        limit: Integer,
        more: bool,
        referrals: ::Array[GrowsurfRuby::ReferralList::Referral],
        next_id: String?,
        next_offset: Integer?
      }

    class ReferralList < GrowsurfRuby::Internal::Type::BaseModel
      attr_accessor limit: Integer

      attr_accessor more: bool

      attr_accessor referrals: ::Array[GrowsurfRuby::ReferralList::Referral]

      attr_accessor next_id: String?

      attr_accessor next_offset: Integer?

      def initialize: (
        limit: Integer,
        more: bool,
        referrals: ::Array[GrowsurfRuby::ReferralList::Referral],
        ?next_id: String?,
        ?next_offset: Integer?
      ) -> void

      def to_hash: -> {
        limit: Integer,
        more: bool,
        referrals: ::Array[GrowsurfRuby::ReferralList::Referral],
        next_id: String?,
        next_offset: Integer?
      }

      type referral =
        {
          id: String,
          created_at: Integer,
          email: String,
          referral_status: GrowsurfRuby::Models::Campaign::referral_status,
          referred_by: String,
          updated_at: Integer,
          first_name: String?,
          last_name: String?
        }

      class Referral < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor created_at: Integer

        attr_accessor email: String

        attr_accessor referral_status: GrowsurfRuby::Models::Campaign::referral_status

        attr_accessor referred_by: String

        attr_accessor updated_at: Integer

        attr_accessor first_name: String?

        attr_accessor last_name: String?

        def initialize: (
          id: String,
          created_at: Integer,
          email: String,
          referral_status: GrowsurfRuby::Models::Campaign::referral_status,
          referred_by: String,
          updated_at: Integer,
          ?first_name: String?,
          ?last_name: String?
        ) -> void

        def to_hash: -> {
          id: String,
          created_at: Integer,
          email: String,
          referral_status: GrowsurfRuby::Models::Campaign::referral_status,
          referred_by: String,
          updated_at: Integer,
          first_name: String?,
          last_name: String?
        }
      end
    end
  end
end
