module GrowsurfRuby
  module Models
    type reward_tax_valuation =
      { fair_market_value_usd: Float?, is_tax_reportable: bool? }

    class RewardTaxValuation < GrowsurfRuby::Internal::Type::BaseModel
      attr_accessor fair_market_value_usd: Float?

      attr_accessor is_tax_reportable: bool?

      def initialize: (
        ?fair_market_value_usd: Float?,
        ?is_tax_reportable: bool?
      ) -> void

      def to_hash: -> {
        fair_market_value_usd: Float?,
        is_tax_reportable: bool?
      }
    end
  end
end
