module GrowsurfRuby
  module Models
    type team_rotate_api_key_response = { api_key: String }

    class TeamRotateAPIKeyResponse < GrowsurfRuby::Internal::Type::BaseModel
      attr_accessor api_key: String

      def initialize: (api_key: String) -> void

      def to_hash: -> { api_key: String }
    end
  end
end
