# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "growsurf_ruby/version"
require_relative "growsurf_ruby/internal/util"
require_relative "growsurf_ruby/internal/type/converter"
require_relative "growsurf_ruby/internal/type/unknown"
require_relative "growsurf_ruby/internal/type/boolean"
require_relative "growsurf_ruby/internal/type/file_input"
require_relative "growsurf_ruby/internal/type/enum"
require_relative "growsurf_ruby/internal/type/union"
require_relative "growsurf_ruby/internal/type/array_of"
require_relative "growsurf_ruby/internal/type/hash_of"
require_relative "growsurf_ruby/internal/type/base_model"
require_relative "growsurf_ruby/internal/type/base_page"
require_relative "growsurf_ruby/internal/type/request_parameters"
require_relative "growsurf_ruby/internal"
require_relative "growsurf_ruby/request_options"
require_relative "growsurf_ruby/file_part"
require_relative "growsurf_ruby/errors"
require_relative "growsurf_ruby/internal/transport/base_client"
require_relative "growsurf_ruby/internal/transport/pooled_net_requester"
require_relative "growsurf_ruby/client"
require_relative "growsurf_ruby/models/campaign/create"
require_relative "growsurf_ruby/models/campaign/participant"
require_relative "growsurf_ruby/models/campaign/campaign_reward_list_response"
require_relative "growsurf_ruby/models/campaign/commission_approve_params"
require_relative "growsurf_ruby/models/campaign/commission_approve_response"
require_relative "growsurf_ruby/models/campaign/commission_delete_params"
require_relative "growsurf_ruby/models/campaign/commission_delete_response"
require_relative "growsurf_ruby/models/campaign/delete_reward_response"
require_relative "growsurf_ruby/models/campaign/fraud_risk_level"
require_relative "growsurf_ruby/models/campaign/participant_activity_logs_response"
require_relative "growsurf_ruby/models/campaign/participant_add_params"
require_relative "growsurf_ruby/models/campaign/participant_analytics_response"
require_relative "growsurf_ruby/models/campaign/participant_bulk_delete_params"
require_relative "growsurf_ruby/models/campaign/participant_bulk_delete_response"
require_relative "growsurf_ruby/models/campaign/participant_cancel_delayed_referral_params"
require_relative "growsurf_ruby/models/campaign/participant_cancel_delayed_referral_response"
require_relative "growsurf_ruby/models/campaign/participant_delete_params"
require_relative "growsurf_ruby/models/campaign/participant_delete_response"
require_relative "growsurf_ruby/models/campaign/participant_email_params"
require_relative "growsurf_ruby/models/campaign/participant_email_response"
require_relative "growsurf_ruby/models/campaign/participant_list_activity_logs_params"
require_relative "growsurf_ruby/models/campaign/participant_list_commissions_params"
require_relative "growsurf_ruby/models/campaign/participant_list_payouts_params"
require_relative "growsurf_ruby/models/campaign/participant_list_referrals_params"
require_relative "growsurf_ruby/models/campaign/participant_list_rewards_params"
require_relative "growsurf_ruby/models/campaign/participant_list_rewards_response"
require_relative "growsurf_ruby/models/campaign/participant_record_transaction_params"
require_relative "growsurf_ruby/models/campaign/participant_record_transaction_response"
require_relative "growsurf_ruby/models/campaign/participant_refund_transaction_params"
require_relative "growsurf_ruby/models/campaign/participant_refund_transaction_response"
require_relative "growsurf_ruby/models/campaign/participant_retrieve_analytics_params"
require_relative "growsurf_ruby/models/campaign/participant_retrieve_params"
require_relative "growsurf_ruby/models/campaign/participant_reward"
require_relative "growsurf_ruby/models/campaign/participant_send_invites_params"
require_relative "growsurf_ruby/models/campaign/participant_send_invites_response"
require_relative "growsurf_ruby/models/campaign/participant_trigger_referral_params"
require_relative "growsurf_ruby/models/campaign/participant_trigger_referral_response"
require_relative "growsurf_ruby/models/campaign/participant_update_params"
require_relative "growsurf_ruby/models/campaign/referral_source"
require_relative "growsurf_ruby/models/campaign/referral_status"
require_relative "growsurf_ruby/models/campaign/reward"
require_relative "growsurf_ruby/models/campaign/reward_approve_params"
require_relative "growsurf_ruby/models/campaign/reward_approve_response"
require_relative "growsurf_ruby/models/campaign/reward_create_params"
require_relative "growsurf_ruby/models/campaign/reward_delete_params"
require_relative "growsurf_ruby/models/campaign/reward_delete_response"
require_relative "growsurf_ruby/models/campaign/reward_fulfill_params"
require_relative "growsurf_ruby/models/campaign/reward_fulfill_response"
require_relative "growsurf_ruby/models/campaign/reward_update_params"
require_relative "growsurf_ruby/models/campaign/webhook"
require_relative "growsurf_ruby/models/campaign/webhook_create_params"
require_relative "growsurf_ruby/models/campaign/webhook_delete_params"
require_relative "growsurf_ruby/models/campaign/webhook_delete_response"
require_relative "growsurf_ruby/models/campaign/webhook_event"
require_relative "growsurf_ruby/models/campaign/webhook_list_response"
require_relative "growsurf_ruby/models/campaign/webhook_test_params"
require_relative "growsurf_ruby/models/campaign/webhook_test_response"
require_relative "growsurf_ruby/models/campaign/webhook_update_params"
require_relative "growsurf_ruby/models/account"
require_relative "growsurf_ruby/models/account_create_params"
require_relative "growsurf_ruby/models/account_create_response"
require_relative "growsurf_ruby/models/account_resend_verification_email_response"
require_relative "growsurf_ruby/models/account_rotate_api_key_response"
require_relative "growsurf_ruby/models/account_update_params"
require_relative "growsurf_ruby/models/campaign"
require_relative "growsurf_ruby/models/campaign_create_mobile_participant_token_params"
require_relative "growsurf_ruby/models/campaign_create_mobile_participant_token_response"
require_relative "growsurf_ruby/models/campaign_create_params"
require_relative "growsurf_ruby/models/campaign_list_commissions_params"
require_relative "growsurf_ruby/models/campaign_list_leaderboard_params"
require_relative "growsurf_ruby/models/campaign_list_params"
require_relative "growsurf_ruby/models/campaign_list_participants_params"
require_relative "growsurf_ruby/models/campaign_list_payouts_params"
require_relative "growsurf_ruby/models/campaign_list_referrals_params"
require_relative "growsurf_ruby/models/campaign_list_response"
require_relative "growsurf_ruby/models/campaign_retrieve_analytics_params"
require_relative "growsurf_ruby/models/campaign_retrieve_analytics_response"
require_relative "growsurf_ruby/models/campaign_retrieve_params"
require_relative "growsurf_ruby/models/campaign_update_params"
require_relative "growsurf_ruby/models/commission_structure"
require_relative "growsurf_ruby/models/participant_commission_list"
require_relative "growsurf_ruby/models/participant_list"
require_relative "growsurf_ruby/models/participant_payout_list"
require_relative "growsurf_ruby/models/referral_list"
require_relative "growsurf_ruby/models/referral_flow_screenshots_response"
require_relative "growsurf_ruby/models/reward_tax_valuation"
require_relative "growsurf_ruby/models"
require_relative "growsurf_ruby/resources/account"
require_relative "growsurf_ruby/resources/campaign"
require_relative "growsurf_ruby/resources/campaign/commission"
require_relative "growsurf_ruby/resources/campaign/design"
require_relative "growsurf_ruby/resources/campaign/emails"
require_relative "growsurf_ruby/resources/campaign/installation"
require_relative "growsurf_ruby/resources/campaign/options"
require_relative "growsurf_ruby/resources/campaign/participant"
require_relative "growsurf_ruby/resources/campaign/reward"
require_relative "growsurf_ruby/resources/campaign/rewards"
require_relative "growsurf_ruby/resources/campaign/webhooks"
