# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "growsurf/version"
require_relative "growsurf/internal/util"
require_relative "growsurf/internal/type/converter"
require_relative "growsurf/internal/type/unknown"
require_relative "growsurf/internal/type/boolean"
require_relative "growsurf/internal/type/file_input"
require_relative "growsurf/internal/type/enum"
require_relative "growsurf/internal/type/union"
require_relative "growsurf/internal/type/array_of"
require_relative "growsurf/internal/type/hash_of"
require_relative "growsurf/internal/type/base_model"
require_relative "growsurf/internal/type/base_page"
require_relative "growsurf/internal/type/request_parameters"
require_relative "growsurf/internal"
require_relative "growsurf/request_options"
require_relative "growsurf/file_part"
require_relative "growsurf/errors"
require_relative "growsurf/internal/transport/base_client"
require_relative "growsurf/internal/transport/pooled_net_requester"
require_relative "growsurf/client"
require_relative "growsurf/models/campaign/participant"
require_relative "growsurf/models/campaign/commission_approve_params"
require_relative "growsurf/models/campaign/commission_approve_response"
require_relative "growsurf/models/campaign/commission_delete_params"
require_relative "growsurf/models/campaign/commission_delete_response"
require_relative "growsurf/models/campaign/fraud_risk_level"
require_relative "growsurf/models/campaign/participant_add_params"
require_relative "growsurf/models/campaign/participant_delete_params"
require_relative "growsurf/models/campaign/participant_delete_response"
require_relative "growsurf/models/campaign/participant_list_commissions_params"
require_relative "growsurf/models/campaign/participant_list_payouts_params"
require_relative "growsurf/models/campaign/participant_list_referrals_params"
require_relative "growsurf/models/campaign/participant_list_rewards_params"
require_relative "growsurf/models/campaign/participant_list_rewards_response"
require_relative "growsurf/models/campaign/participant_record_transaction_params"
require_relative "growsurf/models/campaign/participant_record_transaction_response"
require_relative "growsurf/models/campaign/participant_retrieve_params"
require_relative "growsurf/models/campaign/participant_reward"
require_relative "growsurf/models/campaign/participant_send_invites_params"
require_relative "growsurf/models/campaign/participant_send_invites_response"
require_relative "growsurf/models/campaign/participant_trigger_referral_params"
require_relative "growsurf/models/campaign/participant_trigger_referral_response"
require_relative "growsurf/models/campaign/participant_update_params"
require_relative "growsurf/models/campaign/referral_source"
require_relative "growsurf/models/campaign/referral_status"
require_relative "growsurf/models/campaign/reward_approve_params"
require_relative "growsurf/models/campaign/reward_approve_response"
require_relative "growsurf/models/campaign/reward_delete_params"
require_relative "growsurf/models/campaign/reward_delete_response"
require_relative "growsurf/models/campaign/reward_fulfill_params"
require_relative "growsurf/models/campaign/reward_fulfill_response"
require_relative "growsurf/models/campaign"
require_relative "growsurf/models/campaign_list_commissions_params"
require_relative "growsurf/models/campaign_list_leaderboard_params"
require_relative "growsurf/models/campaign_list_params"
require_relative "growsurf/models/campaign_list_participants_params"
require_relative "growsurf/models/campaign_list_payouts_params"
require_relative "growsurf/models/campaign_list_referrals_params"
require_relative "growsurf/models/campaign_list_response"
require_relative "growsurf/models/campaign_retrieve_analytics_params"
require_relative "growsurf/models/campaign_retrieve_analytics_response"
require_relative "growsurf/models/campaign_retrieve_params"
require_relative "growsurf/models/commission_structure"
require_relative "growsurf/models/participant_commission_list"
require_relative "growsurf/models/participant_list"
require_relative "growsurf/models/participant_payout_list"
require_relative "growsurf/models/referral_list"
require_relative "growsurf/models"
require_relative "growsurf/resources/campaign"
require_relative "growsurf/resources/campaign/commission"
require_relative "growsurf/resources/campaign/participant"
require_relative "growsurf/resources/campaign/reward"
