module Growsurf
  module Models
    module Campaign
      type commission_approve_params =
        { id: String, commission_id: String }
        & Growsurf::Internal::Type::request_parameters

      class CommissionApproveParams < Growsurf::Internal::Type::BaseModel
        extend Growsurf::Internal::Type::RequestParameters::Converter
        include Growsurf::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor commission_id: String

        def initialize: (
          id: String,
          commission_id: String,
          ?request_options: Growsurf::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          commission_id: String,
          request_options: Growsurf::RequestOptions
        }
      end
    end
  end
end
