module Growsurf
  module Models
    module Campaign
      type campaign_participant =
        {
          id: String,
          email: String,
          monthly_rank: Integer,
          monthly_referral_count: Integer,
          rank: Integer,
          referral_count: Integer,
          rewards: ::Array[Growsurf::Campaign::ParticipantReward],
          share_url: String,
          all_matching_fraudsters: ::Array[::Hash[Symbol, top]],
          created_at: Integer,
          fingerprint: String?,
          first_name: String?,
          fraud_reason_code: String,
          fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
          impression_count: Integer,
          invite_count: Integer,
          ip_address: String?,
          is_new: bool,
          is_winner: bool,
          last_name: String?,
          metadata: ::Hash[Symbol, top],
          monthly_referrals: ::Array[String],
          notes: String?,
          paypal_email_address: String,
          prev_monthly_rank: Integer,
          prev_monthly_referral_count: Integer,
          referrals: ::Array[String],
          referral_source: Growsurf::Models::Campaign::referral_source,
          referral_status: Growsurf::Models::Campaign::referral_status,
          referred_by: String,
          referrer: Growsurf::Campaign::CampaignParticipant::Referrer?,
          share_count: ::Hash[Symbol, Integer],
          unique_impression_count: Integer,
          unread_commissions_count: Integer,
          unread_payouts_count: Integer,
          unsubscribed: bool,
          vanity_keys: ::Array[String]
        }

      class CampaignParticipant < Growsurf::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor email: String

        attr_accessor monthly_rank: Integer

        attr_accessor monthly_referral_count: Integer

        attr_accessor rank: Integer

        attr_accessor referral_count: Integer

        attr_accessor rewards: ::Array[Growsurf::Campaign::ParticipantReward]

        attr_accessor share_url: String

        attr_reader all_matching_fraudsters: ::Array[::Hash[Symbol, top]]?

        def all_matching_fraudsters=: (
          ::Array[::Hash[Symbol, top]]
        ) -> ::Array[::Hash[Symbol, top]]

        attr_reader created_at: Integer?

        def created_at=: (Integer) -> Integer

        attr_accessor fingerprint: String?

        attr_accessor first_name: String?

        attr_reader fraud_reason_code: String?

        def fraud_reason_code=: (String) -> String

        attr_reader fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level?

        def fraud_risk_level=: (
          Growsurf::Models::Campaign::fraud_risk_level
        ) -> Growsurf::Models::Campaign::fraud_risk_level

        attr_reader impression_count: Integer?

        def impression_count=: (Integer) -> Integer

        attr_reader invite_count: Integer?

        def invite_count=: (Integer) -> Integer

        attr_accessor ip_address: String?

        attr_reader is_new: bool?

        def is_new=: (bool) -> bool

        attr_reader is_winner: bool?

        def is_winner=: (bool) -> bool

        attr_accessor last_name: String?

        attr_reader metadata: ::Hash[Symbol, top]?

        def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

        attr_reader monthly_referrals: ::Array[String]?

        def monthly_referrals=: (::Array[String]) -> ::Array[String]

        attr_accessor notes: String?

        attr_reader paypal_email_address: String?

        def paypal_email_address=: (String) -> String

        attr_reader prev_monthly_rank: Integer?

        def prev_monthly_rank=: (Integer) -> Integer

        attr_reader prev_monthly_referral_count: Integer?

        def prev_monthly_referral_count=: (Integer) -> Integer

        attr_reader referrals: ::Array[String]?

        def referrals=: (::Array[String]) -> ::Array[String]

        attr_reader referral_source: Growsurf::Models::Campaign::referral_source?

        def referral_source=: (
          Growsurf::Models::Campaign::referral_source
        ) -> Growsurf::Models::Campaign::referral_source

        attr_reader referral_status: Growsurf::Models::Campaign::referral_status?

        def referral_status=: (
          Growsurf::Models::Campaign::referral_status
        ) -> Growsurf::Models::Campaign::referral_status

        attr_reader referred_by: String?

        def referred_by=: (String) -> String

        attr_accessor referrer: Growsurf::Campaign::CampaignParticipant::Referrer?

        attr_reader share_count: ::Hash[Symbol, Integer]?

        def share_count=: (::Hash[Symbol, Integer]) -> ::Hash[Symbol, Integer]

        attr_reader unique_impression_count: Integer?

        def unique_impression_count=: (Integer) -> Integer

        attr_reader unread_commissions_count: Integer?

        def unread_commissions_count=: (Integer) -> Integer

        attr_reader unread_payouts_count: Integer?

        def unread_payouts_count=: (Integer) -> Integer

        attr_reader unsubscribed: bool?

        def unsubscribed=: (bool) -> bool

        attr_reader vanity_keys: ::Array[String]?

        def vanity_keys=: (::Array[String]) -> ::Array[String]

        def initialize: (
          id: String,
          email: String,
          monthly_rank: Integer,
          monthly_referral_count: Integer,
          rank: Integer,
          referral_count: Integer,
          rewards: ::Array[Growsurf::Campaign::ParticipantReward],
          share_url: String,
          ?all_matching_fraudsters: ::Array[::Hash[Symbol, top]],
          ?created_at: Integer,
          ?fingerprint: String?,
          ?first_name: String?,
          ?fraud_reason_code: String,
          ?fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
          ?impression_count: Integer,
          ?invite_count: Integer,
          ?ip_address: String?,
          ?is_new: bool,
          ?is_winner: bool,
          ?last_name: String?,
          ?metadata: ::Hash[Symbol, top],
          ?monthly_referrals: ::Array[String],
          ?notes: String?,
          ?paypal_email_address: String,
          ?prev_monthly_rank: Integer,
          ?prev_monthly_referral_count: Integer,
          ?referrals: ::Array[String],
          ?referral_source: Growsurf::Models::Campaign::referral_source,
          ?referral_status: Growsurf::Models::Campaign::referral_status,
          ?referred_by: String,
          ?referrer: Growsurf::Campaign::CampaignParticipant::Referrer?,
          ?share_count: ::Hash[Symbol, Integer],
          ?unique_impression_count: Integer,
          ?unread_commissions_count: Integer,
          ?unread_payouts_count: Integer,
          ?unsubscribed: bool,
          ?vanity_keys: ::Array[String]
        ) -> void

        def to_hash: -> {
          id: String,
          email: String,
          monthly_rank: Integer,
          monthly_referral_count: Integer,
          rank: Integer,
          referral_count: Integer,
          rewards: ::Array[Growsurf::Campaign::ParticipantReward],
          share_url: String,
          all_matching_fraudsters: ::Array[::Hash[Symbol, top]],
          created_at: Integer,
          fingerprint: String?,
          first_name: String?,
          fraud_reason_code: String,
          fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
          impression_count: Integer,
          invite_count: Integer,
          ip_address: String?,
          is_new: bool,
          is_winner: bool,
          last_name: String?,
          metadata: ::Hash[Symbol, top],
          monthly_referrals: ::Array[String],
          notes: String?,
          paypal_email_address: String,
          prev_monthly_rank: Integer,
          prev_monthly_referral_count: Integer,
          referrals: ::Array[String],
          referral_source: Growsurf::Models::Campaign::referral_source,
          referral_status: Growsurf::Models::Campaign::referral_status,
          referred_by: String,
          referrer: Growsurf::Campaign::CampaignParticipant::Referrer?,
          share_count: ::Hash[Symbol, Integer],
          unique_impression_count: Integer,
          unread_commissions_count: Integer,
          unread_payouts_count: Integer,
          unsubscribed: bool,
          vanity_keys: ::Array[String]
        }

        type referrer =
          {
            id: String,
            created_at: Integer,
            email: String,
            fingerprint: String?,
            first_name: String?,
            fraud_reason_code: String,
            fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
            impression_count: Integer,
            invite_count: Integer,
            ip_address: String?,
            is_winner: bool,
            last_name: String?,
            metadata: ::Hash[Symbol, top],
            monthly_rank: Integer,
            monthly_referral_count: Integer,
            monthly_referrals: ::Array[String],
            prev_monthly_rank: Integer,
            prev_monthly_referral_count: Integer,
            rank: Integer,
            referral_count: Integer,
            referrals: ::Array[String],
            referral_source: Growsurf::Models::Campaign::referral_source,
            referral_status: Growsurf::Models::Campaign::referral_status,
            share_count: ::Hash[Symbol, Integer],
            share_url: String,
            unique_impression_count: Integer,
            unsubscribed: bool
          }

        class Referrer < Growsurf::Internal::Type::BaseModel
          attr_reader id: String?

          def id=: (String) -> String

          attr_reader created_at: Integer?

          def created_at=: (Integer) -> Integer

          attr_reader email: String?

          def email=: (String) -> String

          attr_accessor fingerprint: String?

          attr_accessor first_name: String?

          attr_reader fraud_reason_code: String?

          def fraud_reason_code=: (String) -> String

          attr_reader fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level?

          def fraud_risk_level=: (
            Growsurf::Models::Campaign::fraud_risk_level
          ) -> Growsurf::Models::Campaign::fraud_risk_level

          attr_reader impression_count: Integer?

          def impression_count=: (Integer) -> Integer

          attr_reader invite_count: Integer?

          def invite_count=: (Integer) -> Integer

          attr_accessor ip_address: String?

          attr_reader is_winner: bool?

          def is_winner=: (bool) -> bool

          attr_accessor last_name: String?

          attr_reader metadata: ::Hash[Symbol, top]?

          def metadata=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

          attr_reader monthly_rank: Integer?

          def monthly_rank=: (Integer) -> Integer

          attr_reader monthly_referral_count: Integer?

          def monthly_referral_count=: (Integer) -> Integer

          attr_reader monthly_referrals: ::Array[String]?

          def monthly_referrals=: (::Array[String]) -> ::Array[String]

          attr_reader prev_monthly_rank: Integer?

          def prev_monthly_rank=: (Integer) -> Integer

          attr_reader prev_monthly_referral_count: Integer?

          def prev_monthly_referral_count=: (Integer) -> Integer

          attr_reader rank: Integer?

          def rank=: (Integer) -> Integer

          attr_reader referral_count: Integer?

          def referral_count=: (Integer) -> Integer

          attr_reader referrals: ::Array[String]?

          def referrals=: (::Array[String]) -> ::Array[String]

          attr_reader referral_source: Growsurf::Models::Campaign::referral_source?

          def referral_source=: (
            Growsurf::Models::Campaign::referral_source
          ) -> Growsurf::Models::Campaign::referral_source

          attr_reader referral_status: Growsurf::Models::Campaign::referral_status?

          def referral_status=: (
            Growsurf::Models::Campaign::referral_status
          ) -> Growsurf::Models::Campaign::referral_status

          attr_reader share_count: ::Hash[Symbol, Integer]?

          def share_count=: (::Hash[Symbol, Integer]) -> ::Hash[Symbol, Integer]

          attr_reader share_url: String?

          def share_url=: (String) -> String

          attr_reader unique_impression_count: Integer?

          def unique_impression_count=: (Integer) -> Integer

          attr_reader unsubscribed: bool?

          def unsubscribed=: (bool) -> bool

          def initialize: (
            ?id: String,
            ?created_at: Integer,
            ?email: String,
            ?fingerprint: String?,
            ?first_name: String?,
            ?fraud_reason_code: String,
            ?fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
            ?impression_count: Integer,
            ?invite_count: Integer,
            ?ip_address: String?,
            ?is_winner: bool,
            ?last_name: String?,
            ?metadata: ::Hash[Symbol, top],
            ?monthly_rank: Integer,
            ?monthly_referral_count: Integer,
            ?monthly_referrals: ::Array[String],
            ?prev_monthly_rank: Integer,
            ?prev_monthly_referral_count: Integer,
            ?rank: Integer,
            ?referral_count: Integer,
            ?referrals: ::Array[String],
            ?referral_source: Growsurf::Models::Campaign::referral_source,
            ?referral_status: Growsurf::Models::Campaign::referral_status,
            ?share_count: ::Hash[Symbol, Integer],
            ?share_url: String,
            ?unique_impression_count: Integer,
            ?unsubscribed: bool
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Integer,
            email: String,
            fingerprint: String?,
            first_name: String?,
            fraud_reason_code: String,
            fraud_risk_level: Growsurf::Models::Campaign::fraud_risk_level,
            impression_count: Integer,
            invite_count: Integer,
            ip_address: String?,
            is_winner: bool,
            last_name: String?,
            metadata: ::Hash[Symbol, top],
            monthly_rank: Integer,
            monthly_referral_count: Integer,
            monthly_referrals: ::Array[String],
            prev_monthly_rank: Integer,
            prev_monthly_referral_count: Integer,
            rank: Integer,
            referral_count: Integer,
            referrals: ::Array[String],
            referral_source: Growsurf::Models::Campaign::referral_source,
            referral_status: Growsurf::Models::Campaign::referral_status,
            share_count: ::Hash[Symbol, Integer],
            share_url: String,
            unique_impression_count: Integer,
            unsubscribed: bool
          }
        end
      end
    end
  end
end
