module Growsurf
  module Models
    type campaign_list_response = { campaigns: ::Array[Growsurf::CampaignAPI] }

    class CampaignListResponse < Growsurf::Internal::Type::BaseModel
      attr_accessor campaigns: ::Array[Growsurf::CampaignAPI]

      def initialize: (campaigns: ::Array[Growsurf::CampaignAPI]) -> void

      def to_hash: -> { campaigns: ::Array[Growsurf::CampaignAPI] }
    end
  end
end
