module Growsurf
  module Models
    type campaign_retrieve_params =
      { id: String } & Growsurf::Internal::Type::request_parameters

    class CampaignRetrieveParams < Growsurf::Internal::Type::BaseModel
      extend Growsurf::Internal::Type::RequestParameters::Converter
      include Growsurf::Internal::Type::RequestParameters

      attr_accessor id: String

      def initialize: (
        id: String,
        ?request_options: Growsurf::request_opts
      ) -> void

      def to_hash: -> { id: String, request_options: Growsurf::RequestOptions }
    end
  end
end
