module Growsurf
  module Models
    type campaign_list_params =
      {  } & Growsurf::Internal::Type::request_parameters

    class CampaignListParams < Growsurf::Internal::Type::BaseModel
      extend Growsurf::Internal::Type::RequestParameters::Converter
      include Growsurf::Internal::Type::RequestParameters

      def initialize: (?request_options: Growsurf::request_opts) -> void

      def to_hash: -> { request_options: Growsurf::RequestOptions }
    end
  end
end
