module Growsurf
  module Models
    type campaign_list_commissions_params =
      {
        id: String,
        limit: Integer,
        next_id: String,
        status: Growsurf::Models::CampaignListCommissionsParams::status
      }
      & Growsurf::Internal::Type::request_parameters

    class CampaignListCommissionsParams < Growsurf::Internal::Type::BaseModel
      extend Growsurf::Internal::Type::RequestParameters::Converter
      include Growsurf::Internal::Type::RequestParameters

      attr_accessor id: String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader next_id: String?

      def next_id=: (String) -> String

      attr_reader status: Growsurf::Models::CampaignListCommissionsParams::status?

      def status=: (
        Growsurf::Models::CampaignListCommissionsParams::status
      ) -> Growsurf::Models::CampaignListCommissionsParams::status

      def initialize: (
        id: String,
        ?limit: Integer,
        ?next_id: String,
        ?status: Growsurf::Models::CampaignListCommissionsParams::status,
        ?request_options: Growsurf::request_opts
      ) -> void

      def to_hash: -> {
        id: String,
        limit: Integer,
        next_id: String,
        status: Growsurf::Models::CampaignListCommissionsParams::status,
        request_options: Growsurf::RequestOptions
      }

      type status = :PENDING | :APPROVED | :PAID | :REVERSED | :DELETED

      module Status
        extend Growsurf::Internal::Type::Enum

        PENDING: :PENDING
        APPROVED: :APPROVED
        PAID: :PAID
        REVERSED: :REVERSED
        DELETED: :DELETED

        def self?.values: -> ::Array[Growsurf::Models::CampaignListCommissionsParams::status]
      end
    end
  end
end
