module Growsurf
  module Resources
    class Campaign
      class Reward
        def delete: (
          String reward_id,
          id: String,
          ?request_options: Growsurf::request_opts
        ) -> Growsurf::Models::Campaign::RewardDeleteResponse

        def approve: (
          String reward_id,
          id: String,
          ?fulfill: bool,
          ?request_options: Growsurf::request_opts
        ) -> Growsurf::Models::Campaign::RewardApproveResponse

        def fulfill: (
          String reward_id,
          id: String,
          ?request_options: Growsurf::request_opts
        ) -> Growsurf::Models::Campaign::RewardFulfillResponse

        def initialize: (client: Growsurf::Client) -> void
      end
    end
  end
end
