module Growsurf
  module Resources
    class Campaign
      attr_reader participant: Growsurf::Resources::Campaign::Participant

      attr_reader reward: Growsurf::Resources::Campaign::Reward

      attr_reader commission: Growsurf::Resources::Campaign::Commission

      def retrieve: (
        String id,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::CampaignAPI

      def list: (
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::Models::CampaignListResponse

      def list_commissions: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?status: Growsurf::Models::CampaignListCommissionsParams::status,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::ParticipantCommissionList

      def list_leaderboard: (
        String id,
        ?is_monthly: bool,
        ?leaderboard_type: Growsurf::Models::CampaignListLeaderboardParams::leaderboard_type,
        ?limit: Integer,
        ?next_id: String,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::ParticipantList

      def list_participants: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::ParticipantList

      def list_payouts: (
        String id,
        ?limit: Integer,
        ?next_id: String,
        ?status: Growsurf::Models::CampaignListPayoutsParams::status,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::ParticipantPayoutList

      def list_referrals: (
        String id,
        ?desc: bool,
        ?email: String,
        ?first_name: String,
        ?last_name: String,
        ?limit: Integer,
        ?next_id: String,
        ?offset: Integer,
        ?referral_status: Growsurf::Models::Campaign::referral_status,
        ?sort_by: Growsurf::Models::CampaignListReferralsParams::sort_by,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::ReferralList

      def retrieve_analytics: (
        String id,
        ?days: Integer,
        ?end_date: Integer,
        ?start_date: Integer,
        ?request_options: Growsurf::request_opts
      ) -> Growsurf::Models::CampaignRetrieveAnalyticsResponse

      def initialize: (client: Growsurf::Client) -> void
    end
  end
end
