module GrowsurfRuby
  module Models
    module Campaign
      type participant_get_payout_destination_response =
        {
          active_provider: String?,
          destinations: ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination],
          enabled_providers: ::Array[String]
        }

      class ParticipantGetPayoutDestinationResponse < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor active_provider: String?

        attr_reader destinations: ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination]

        def destinations=: (
          ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination]
        ) -> ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination]

        attr_reader enabled_providers: ::Array[String]

        def enabled_providers=: (::Array[String]) -> ::Array[String]

        def initialize: (
          active_provider: String?,
          destinations: ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination],
          enabled_providers: ::Array[String]
        ) -> void

        def to_hash: -> {
          active_provider: String?,
          destinations: ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination],
          enabled_providers: ::Array[String]
        }

        type destination =
          {
            claim_email: String?,
            confirmed_at: Integer?,
            legal_entity_type: GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination::legal_entity_type?,
            needs_repair_reason: String?,
            provider: String,
            provider_display_name: String,
            status: String
          }

        class Destination < GrowsurfRuby::Internal::Type::BaseModel
          attr_accessor claim_email: String?

          attr_accessor confirmed_at: Integer?

          attr_accessor legal_entity_type: GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination::legal_entity_type?

          attr_accessor needs_repair_reason: String?

          attr_reader provider: String

          def provider=: (String) -> String

          attr_reader provider_display_name: String

          def provider_display_name=: (String) -> String

          attr_reader status: String

          def status=: (String) -> String

          def initialize: (
            claim_email: String?,
            confirmed_at: Integer?,
            legal_entity_type: GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination::legal_entity_type?,
            needs_repair_reason: String?,
            provider: String,
            provider_display_name: String,
            status: String
          ) -> void

          def to_hash: -> {
            claim_email: String?,
            confirmed_at: Integer?,
            legal_entity_type: GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination::legal_entity_type?,
            needs_repair_reason: String?,
            provider: String,
            provider_display_name: String,
            status: String
          }

          type legal_entity_type = :INDIVIDUAL | :BUSINESS

          module LegalEntityType
            extend GrowsurfRuby::Internal::Type::Enum

            INDIVIDUAL: :INDIVIDUAL
            BUSINESS: :BUSINESS

            def self?.values: -> ::Array[GrowsurfRuby::Models::Campaign::ParticipantGetPayoutDestinationResponse::Destination::legal_entity_type]
          end
        end
      end
    end
  end
end
