module GrowsurfRuby
  module Models
    module Campaign
      type participant_send_invites_response =
        { invites_sent: Integer, message_type: String, success: bool }

      class ParticipantSendInvitesResponse < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor invites_sent: Integer

        attr_accessor message_type: String

        attr_accessor success: bool

        def initialize: (
          invites_sent: Integer,
          message_type: String,
          success: bool
        ) -> void

        def to_hash: -> {
          invites_sent: Integer,
          message_type: String,
          success: bool
        }
      end
    end
  end
end
