module GrowsurfRuby
  module Models
    module Campaign
      type participant_list_rewards_params =
        {
          id: String,
          participant_id_or_email: String,
          limit: Integer,
          next_id: String
        }
        & GrowsurfRuby::Internal::Type::request_parameters

      class ParticipantListRewardsParams < GrowsurfRuby::Internal::Type::BaseModel
        extend GrowsurfRuby::Internal::Type::RequestParameters::Converter
        include GrowsurfRuby::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor participant_id_or_email: String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader next_id: String?

        def next_id=: (String) -> String

        def initialize: (
          id: String,
          participant_id_or_email: String,
          ?limit: Integer,
          ?next_id: String,
          ?request_options: GrowsurfRuby::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          participant_id_or_email: String,
          limit: Integer,
          next_id: String,
          request_options: GrowsurfRuby::RequestOptions
        }
      end
    end
  end
end
