module GrowsurfRuby
  module Models
    module Campaign
      type participant_delete_response = { success: bool }

      class ParticipantDeleteResponse < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor success: bool

        def initialize: (success: bool) -> void

        def to_hash: -> { success: bool }
      end
    end
  end
end
