module GrowsurfRuby
  module Models
    module Campaign
      type participant_delete_params =
        { id: String, participant_id_or_email: String }
        & GrowsurfRuby::Internal::Type::request_parameters

      class ParticipantDeleteParams < GrowsurfRuby::Internal::Type::BaseModel
        extend GrowsurfRuby::Internal::Type::RequestParameters::Converter
        include GrowsurfRuby::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor participant_id_or_email: String

        def initialize: (
          id: String,
          participant_id_or_email: String,
          ?request_options: GrowsurfRuby::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          participant_id_or_email: String,
          request_options: GrowsurfRuby::RequestOptions
        }
      end
    end
  end
end
