module GrowsurfRuby
  module Models
    module Campaign
      type reward =
        {
          id: String,
          is_unlimited: bool,
          metadata: ::Hash[Symbol, top],
          type: GrowsurfRuby::Models::Campaign::Reward::type_,
          commission_structure: GrowsurfRuby::CommissionStructure?,
          conversions_required: Integer?,
          coupon_code: String?,
          description: String?,
          image_url: String?,
          limit: Integer?,
          limit_duration: GrowsurfRuby::Models::Campaign::Reward::limit_duration?,
          next_milestone_prefix: String?,
          next_milestone_suffix: String?,
          number_of_winners: Integer?,
          order: Integer?,
          referral_coupon_code: String?,
          referral_description: String?,
          referred_reward_upfront: bool,
          referred_value: GrowsurfRuby::RewardTaxValuation?,
          value: GrowsurfRuby::RewardTaxValuation?
        }

      class Reward < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor is_unlimited: bool

        attr_accessor metadata: ::Hash[Symbol, top]

        attr_accessor type: GrowsurfRuby::Models::Campaign::Reward::type_

        attr_accessor commission_structure: GrowsurfRuby::CommissionStructure?

        attr_accessor conversions_required: Integer?

        attr_accessor coupon_code: String?

        attr_accessor description: String?

        attr_accessor image_url: String?

        attr_accessor limit: Integer?

        attr_accessor limit_duration: GrowsurfRuby::Models::Campaign::Reward::limit_duration?

        attr_accessor next_milestone_prefix: String?

        attr_accessor next_milestone_suffix: String?

        attr_accessor number_of_winners: Integer?

        attr_accessor order: Integer?

        attr_accessor referral_coupon_code: String?

        attr_accessor referral_description: String?

        attr_reader referred_reward_upfront: bool?

        def referred_reward_upfront=: (bool) -> bool

        attr_accessor referred_value: GrowsurfRuby::RewardTaxValuation?

        attr_accessor value: GrowsurfRuby::RewardTaxValuation?

        def initialize: (
          id: String,
          is_unlimited: bool,
          metadata: ::Hash[Symbol, top],
          type: GrowsurfRuby::Models::Campaign::Reward::type_,
          ?commission_structure: GrowsurfRuby::CommissionStructure?,
          ?conversions_required: Integer?,
          ?coupon_code: String?,
          ?description: String?,
          ?image_url: String?,
          ?limit: Integer?,
          ?limit_duration: GrowsurfRuby::Models::Campaign::Reward::limit_duration?,
          ?next_milestone_prefix: String?,
          ?next_milestone_suffix: String?,
          ?number_of_winners: Integer?,
          ?order: Integer?,
          ?referral_coupon_code: String?,
          ?referral_description: String?,
          ?referred_reward_upfront: bool,
          ?referred_value: GrowsurfRuby::RewardTaxValuation?,
          ?value: GrowsurfRuby::RewardTaxValuation?
        ) -> void

        def to_hash: -> {
          id: String,
          is_unlimited: bool,
          metadata: ::Hash[Symbol, top],
          type: GrowsurfRuby::Models::Campaign::Reward::type_,
          commission_structure: GrowsurfRuby::CommissionStructure?,
          conversions_required: Integer?,
          coupon_code: String?,
          description: String?,
          image_url: String?,
          limit: Integer?,
          limit_duration: GrowsurfRuby::Models::Campaign::Reward::limit_duration?,
          next_milestone_prefix: String?,
          next_milestone_suffix: String?,
          number_of_winners: Integer?,
          order: Integer?,
          referral_coupon_code: String?,
          referral_description: String?,
          referred_reward_upfront: bool,
          referred_value: GrowsurfRuby::RewardTaxValuation?,
          value: GrowsurfRuby::RewardTaxValuation?
        }

        type type_ =
          :SINGLE_SIDED | :DOUBLE_SIDED | :MILESTONE | :LEADERBOARD | :AFFILIATE

        module Type
          extend GrowsurfRuby::Internal::Type::Enum

          SINGLE_SIDED: :SINGLE_SIDED
          DOUBLE_SIDED: :DOUBLE_SIDED
          MILESTONE: :MILESTONE
          LEADERBOARD: :LEADERBOARD
          AFFILIATE: :AFFILIATE

          def self?.values: -> ::Array[GrowsurfRuby::Models::Campaign::Reward::type_]
        end

        type limit_duration = :IN_TOTAL | :PER_MONTH | :PER_YEAR

        module LimitDuration
          extend GrowsurfRuby::Internal::Type::Enum

          IN_TOTAL: :IN_TOTAL
          PER_MONTH: :PER_MONTH
          PER_YEAR: :PER_YEAR

          def self?.values: -> ::Array[GrowsurfRuby::Models::Campaign::Reward::limit_duration]
        end
      end
    end
  end
end
