module GrowsurfRuby
  module Models
    module Campaign
      type webhook_delete_params =
        { id: String, webhook_id: String }
        & GrowsurfRuby::Internal::Type::request_parameters

      class WebhookDeleteParams < GrowsurfRuby::Internal::Type::BaseModel
        extend GrowsurfRuby::Internal::Type::RequestParameters::Converter
        include GrowsurfRuby::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_accessor webhook_id: String

        def initialize: (
          id: String,
          webhook_id: String,
          ?request_options: GrowsurfRuby::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          webhook_id: String,
          request_options: GrowsurfRuby::RequestOptions
        }
      end
    end
  end
end
