module GrowsurfRuby
  module Models
    module Campaign
      type webhook_list_response =
        { webhooks: ::Array[GrowsurfRuby::Campaign::Webhook] }

      class WebhookListResponse < GrowsurfRuby::Internal::Type::BaseModel
        attr_accessor webhooks: ::Array[GrowsurfRuby::Campaign::Webhook]

        def initialize: (
          webhooks: ::Array[GrowsurfRuby::Campaign::Webhook]
        ) -> void

        def to_hash: -> { webhooks: ::Array[GrowsurfRuby::Campaign::Webhook] }
      end
    end
  end
end
